### ISSUE TITLE
Host on hex.pm for use in Elixir projects

### ISSUE THREAD

**Issue by lpil** [krestenkrab/triq#53]
Hello!

The Elixir test library ExCheck provides a Elixir-y wrapper around this excellent library. It would be  great if triq was hosted as a package on the [hex.pm](http://hex.pm) package manager, so the mix build tool could automatically handle the dependencies for us Elixir users (and possibly Erlang users too in future).

See here: parroty/excheck#10

Thanks,
Louis

**Comment by h4cc** [comment]
:+1:

**Comment by angelman** [comment]
:purple_heart:
